// SPDX-License-Identifier: proprietary
//
// Unity entry point. Add new test functions here as the suite grows.

#include "unity.h"

extern "C" {

// test_bms_service.cpp
void test_cell_open_range_budget_under_500ms(void);
void test_module_loss_budget_under_500ms(void);
void test_bms_open_wire_flags_module(void);
void test_bms_open_wire_pec_glitch_signals_retry(void);
void test_bms_open_wire_retry_preserves_confirmed_open(void);
void test_bms_capture_adow_raw_decodes_grids(void);
void test_bms_capture_cell_raw_decodes_grid(void);
void test_bms_ltc_clean_response_decodes_all_cells(void);
void test_bms_tap_artifact_does_not_trip_ov(void);
void test_bms_real_overvoltage_not_masked(void);
void test_bms_nonphysical_without_compensation_not_masked(void);
void test_bms_ltc_pec_fail_on_one_ic_marks_module_stale(void);
void test_bms_ltc_pec_fail_increments_error_counter(void);
void test_bms_ltc_short_buffer_rejected(void);
void test_bms_ltc_null_buffer_rejected(void);
void test_bms_ltc_is_healthy_false_after_staleness(void);
void test_bms_mask_collapses_when_chain_stops_responding(void);
void test_bms_mask_clears_only_stale_modules(void);
void test_bms_temp_sweep_room_temp_on_one_channel(void);
void test_bms_temp_hotter_voltage_gives_hotter_reading(void);
void test_bms_temp_rail_reading_skips_slot(void);
void test_bms_temp_pec_fail_skips_slot(void);
void test_bms_temp_bad_channel_idx_rejected(void);
void test_bms_temp_disconnect_debounce(void);
void test_bms_temp_partial_rail_open_is_disconnect(void);
void test_bms_unpopulated_channel_is_not_a_disconnect(void);
void test_bms_required_channel_open_at_boot_faults(void);
void test_temp_disconnect_budget_under_500ms(void);
void test_bms_temp_short_buffer_rejected(void);
void test_bms_per_module_v_aggregates_after_clean_response(void);
void test_bms_per_module_tmax_after_temp_sweep(void);

// test_acu_tx_encoders.cpp
void test_acu_tx_ok_precharge_high_in_run(void);
void test_acu_tx_ok_precharge_high_in_charge(void);
void test_acu_tx_ok_precharge_low_in_start(void);
void test_acu_tx_ok_precharge_low_in_precharge_and_transition(void);
void test_acu_tx_ok_precharge_low_in_error(void);
void test_acu_tx_min_voltage_big_endian(void);
void test_acu_tx_vmin_module_a_layout(void);
void test_acu_tx_vmin_module_b_layout(void);
void test_acu_tx_vmax_module_a_layout(void);
void test_acu_tx_vmax_module_b_layout(void);
void test_acu_tx_currents_zero(void);
void test_acu_tx_currents_positive_pack(void);
void test_acu_tx_currents_negative_pack_two_complement(void);
void test_acu_tx_currents_rounding_to_nearest_dA(void);
void test_acu_tx_currents_saturates_at_int16_extremes(void);
void test_acu_tx_currents_dcdc_in_bytes_2_3(void);
void test_acu_tx_tmax_module_a_layout(void);
void test_acu_tx_tmax_module_b_includes_dcdc_stub(void);
void test_acu_tx_tmax_handles_negative_degC(void);
void test_acu_tx_soc_stub_returns_unknown_sentinel(void);

// test_current_service.cpp
void test_current_adc_zero_point_reads_near_zero(void);
void test_current_adc_discharge_positive(void);
void test_current_adc_charge_negative(void);
void test_current_adc_symmetric_around_zero(void);
void test_current_adc_over_limit_is_observable(void);
void test_current_adc_full_scale_rails(void);
void test_current_dcdc_zero_and_discharge(void);
void test_current_leg_voltage_window(void);
void test_current_update_sets_sensor_fault(void);
void test_current_is_dcdc_fresh_lifecycle(void);

// test_vehicle_service.cpp
void test_decode_dc_bus_little_endian(void);
void test_update_dc_bus_frame(void);
void test_dc_bus_byte2_bits_decode(void);
void test_dc_bus_dlc2_defaults_are_asymmetric(void);
void test_acu_frame_on_wrong_bus_rejected(void);
void test_acu_unknown_id_rejected(void);
void test_charge_req_magic_frame_sets_tick(void);
void test_charge_req_wrong_magic_ignored(void);
void test_charge_requested_freshness(void);
void test_balance_override_balo_off(void);
void test_balance_override_baln_on(void);
void test_balance_override_balx_auto(void);
void test_balance_override_wrong_magic_ignored(void);
void test_balance_effective_cmd_freshness(void);
void test_balance_modules_decode(void);
void test_balance_modules_wrong_magic_ignored(void);
void test_balance_modules_effective_freshness(void);

// test_isotp.cpp
void test_isotp_round_trip_single_frame(void);
void test_isotp_round_trip_first_multiframe(void);
void test_isotp_round_trip_sequence_wrap(void);
void test_isotp_round_trip_max_message(void);
void test_isotp_segmenter_pins_wire_encoding(void);
void test_isotp_flow_control_frame_format(void);
void test_isotp_ff_raises_flow_control_pending(void);
void test_isotp_rejects_bad_single_frame_length(void);
void test_isotp_rejects_first_frame_that_should_be_single(void);
void test_isotp_rejects_oversized_message(void);
void test_isotp_rejects_consecutive_without_first(void);
void test_isotp_rejects_out_of_order_sequence(void);
void test_isotp_rejects_consecutive_from_other_peer(void);
void test_isotp_reassembly_times_out(void);
void test_isotp_idle_never_times_out(void);
void test_isotp_ignores_received_flow_control(void);
void test_isotp_recovers_after_error(void);
void test_isotp_segmenter_rejects_invalid_input(void);

// test_diag_proto.cpp
void test_diag_msgtype_app_ctrl_is_0x06(void);
void test_diag_logfs_opcodes(void);
void test_diag_nack_codes_do_not_collide_with_bootloader(void);
void test_diag_logfs_entry_is_22_bytes(void);
void test_diag_list_batch_fits_one_isotp_message(void);
void test_diag_put_u16_is_little_endian(void);
void test_diag_put_u32_is_little_endian(void);
void test_diag_le_helpers_handle_extremes(void);
void test_diag_parse_request_extracts_type_opcode_args(void);
void test_diag_parse_request_no_args(void);
void test_diag_parse_request_rejects_runt(void);
void test_diag_parse_request_flags_non_app_ctrl(void);
void test_diag_build_ack_frames_type_and_opcode(void);
void test_diag_build_ack_empty_payload(void);
void test_diag_build_ack_refuses_overflow(void);
void test_diag_build_nack_is_three_bytes(void);
void test_diag_session_starts_closed(void);
void test_diag_session_connect_disconnect(void);
void test_diag_session_rejects_other_peer(void);
void test_diag_session_expires_when_host_walks_away(void);
void test_diag_session_traffic_refreshes_idle_timer(void);

// test_logfs_server.cpp
void test_logfs_list_returns_all_entries(void);
void test_logfs_list_entry_layout(void);
void test_logfs_list_cursor_past_end_is_empty(void);
void test_logfs_list_paginates_when_reply_is_full(void);
void test_logfs_list_fs_error_nacks(void);
void test_logfs_open_returns_handle_and_size(void);
void test_logfs_open_missing_file_nacks(void);
void test_logfs_reopen_supersedes_and_closes_previous(void);
void test_logfs_close_releases_handle(void);
void test_logfs_release_closes_open_file(void);
void test_logfs_read_returns_requested_bytes(void);
void test_logfs_read_past_eof_is_short_ack_not_error(void);
void test_logfs_read_clamps_oversized_request(void);
void test_logfs_read_with_stale_handle_nacks(void);
void test_logfs_read_without_open_nacks(void);
void test_logfs_read_io_error_nacks(void);
void test_logfs_read_truncated_args_nacks(void);
void test_logfs_crc_returns_value(void);
void test_logfs_crc_error_nacks(void);
void test_logfs_no_card_nacks_every_opcode(void);
void test_logfs_owns_only_its_opcodes(void);
void test_logfs_unknown_opcode_nacks_unsupported(void);
void test_logfs_full_file_pull_sequence(void);
void test_logfs_open_reply_is_ten_bytes(void);
void test_logfs_open_reports_zero_crc_when_no_sidecar(void);
void test_logfs_finalize_seals_and_returns_index(void);
void test_logfs_finalize_refuses_when_nothing_written(void);
void test_logfs_finalize_releases_open_handle(void);
void test_logfs_finalize_no_card_nacks(void);
void test_logfs_owns_finalize_but_not_delete(void);

// test_crc32.cpp
void test_crc32_check_vector(void);
void test_crc32_empty_is_zero(void);
void test_crc32_short_vectors(void);
void test_crc32_csv_header_shape(void);
void test_crc32_zero_filled_block(void);
void test_crc32_incremental_matches_one_shot(void);
void test_crc32_byte_at_a_time_matches(void);
void test_crc32_zero_length_update_is_identity(void);
void test_crc32_finalize_is_not_idempotent(void);
void test_crc32_detects_single_bit_flip(void);
void test_crc32_detects_reordering(void);

// test_diag_dispatch.cpp
void test_dispatch_ignores_bootloader_namespace(void);
void test_dispatch_ignores_runt_message(void);
void test_dispatch_refuses_logfs_without_session(void);
void test_dispatch_connect_then_logfs_reaches_server(void);
void test_dispatch_refuses_logfs_from_other_peer(void);
void test_dispatch_new_connect_takes_over_and_releases(void);
void test_dispatch_connect_is_idempotent(void);
void test_dispatch_disconnect_releases_and_closes_session(void);
void test_dispatch_disconnect_without_session_still_acks(void);
void test_dispatch_tick_expires_session_and_releases(void);
void test_dispatch_traffic_keeps_long_transfer_alive(void);
void test_dispatch_unknown_opcode_nacks(void);
void test_dispatch_delete_opcode_is_unsupported(void);
void test_dispatch_session_check_precedes_opcode_check(void);
void test_dispatch_connect_ack_carries_protocol_version(void);
void test_dispatch_refuses_logfs_with_ts_live(void);
void test_dispatch_allows_logfs_in_start(void);
void test_dispatch_gate_covers_every_logfs_opcode(void);
void test_dispatch_session_ops_work_in_any_state(void);
void test_dispatch_releases_handle_when_car_goes_live(void);
void test_dispatch_error_state_is_permitted(void);
void test_dispatch_permitted_states_are_ts_down(void);

// test_bootloader.cpp
void test_bootloader_trigger_exact_match(void);
void test_bootloader_reboot_only_when_contactors_open(void);
void test_bootloader_trigger_still_matches_while_energised(void);
void test_bootloader_trigger_wrong_bus(void);
void test_bootloader_trigger_wrong_id(void);
void test_bootloader_trigger_wrong_dlc(void);
void test_bootloader_trigger_each_magic_byte_flipped(void);
void test_bootloader_trigger_trailing_bytes_ignored(void);

// test_can_busoff_recovery.cpp
void test_busoff_healthy_bus_never_attempts(void);
void test_busoff_first_detection_attempts_immediately(void);
void test_busoff_sustained_is_rate_limited(void);
void test_busoff_boundary_exactly_retry_ms_attempts(void);
void test_busoff_steady_cadence_of_attempts(void);
void test_busoff_recovers_then_refaults_attempts_immediately(void);
void test_busoff_tick_wrap_preserves_spacing(void);

// test_safety_predicates.cpp
void test_predicates_nominal_no_fault(void);
void test_predicates_force_error(void);
void test_predicates_cell_undervoltage(void);
void test_predicates_cell_overvoltage(void);
void test_predicates_cell_overtemp(void);
void test_predicates_bms_stale(void);
void test_predicates_current_overlimit(void);
void test_predicates_current_stale(void);
void test_predicates_vcu_stale(void);
void test_predicates_temp_sensor_disconnected(void);
void test_predicates_temp_disconnect_independent_of_temp_trust(void);
void test_predicates_no_disconnect_no_fault(void);
void test_predicates_cell_open_wire_follows_flag(void);
// test_open_wire.cpp
void test_adow_cmd_encoding(void);
void test_open_wire_none_when_healthy(void);
void test_open_wire_interior_conductor(void);
void test_open_wire_endpoints(void);
void test_open_wire_bench_healthy_no_false_positive(void);
void test_open_wire_bench_open_conductor_detected(void);
void test_open_wire_conductor_to_cell_mapping(void);
void test_open_wire_input_guards(void);
void test_predicates_disconnect_is_immediate_not_range_debounced(void);
void test_predicates_boot_grace_suppresses_data_predicates(void);
void test_predicates_boot_grace_does_not_suppress_force_error(void);
void test_predicates_after_grace_zero_ticks_faults(void);
void test_predicates_future_tick_not_stale(void);
void test_predicates_tick_age_clamps_future(void);
void test_predicates_reason_none_when_nominal(void);
void test_predicates_reason_force_error(void);
void test_predicates_reason_bms_stale_reports_module(void);
void test_predicates_reason_current_stale(void);
void test_predicates_reason_vcu_stale(void);
void test_predicates_vcu_stale_exempt_when_not_car(void);
void test_predicates_charger_stale_faults_in_charger_mode(void);
void test_predicates_charger_stale_exempt_when_not_charger(void);
void test_fsm_error_reason_charger_tsms_open(void);
void test_predicates_undervoltage_suppressed_before_first_poll(void);
void test_predicates_undervoltage_armed_reports_module(void);
void test_predicates_offline_module_trips_regardless_of_gate(void);
void test_module_below_sentinel_when_none(void);
void test_is_cell_range_reason(void);
void test_cell_debounce_confirms_after_n(void);
void test_cell_debounce_transient_never_confirms(void);
void test_cell_debounce_reason_change_resets(void);
void test_cell_debounce_ignores_non_cell(void);
void test_bms_stale_debounce_confirms_after_n(void);
void test_bms_stale_debounce_transient_never_confirms(void);
void test_bms_stale_debounce_resets_on_other_reason(void);
void test_ams_ok_low_during_grace(void);
void test_ams_ok_high_when_healthy_post_grace(void);
void test_ams_ok_low_when_latched(void);

// test_dsl_parity.cpp
void test_dsl_status_matches_handrolled(void);
void test_dsl_status_roundtrip(void);
void test_dsl_pack_matches_handrolled_discharge(void);
void test_dsl_pack_matches_handrolled_charge(void);
void test_dsl_pack_roundtrip_signed(void);
void test_dsl_temps_matches_handrolled(void);
void test_dsl_temps_roundtrip_negative(void);
void test_dsl_relay_status_matches_handrolled(void);
void test_dsl_registry_well_formed(void);
void test_dsl_descriptors_match_committed_dbc(void);
void test_dsl_array_descriptors_match_committed_dbc(void);

// test_state_machine.cpp
void test_fsm_start_waits_without_tsms_or_dash_chg(void);
void test_fsm_start_waits_with_tsms_only(void);
void test_fsm_start_waits_with_dash_chg_only(void);
void test_fsm_start_to_precharge_on_both_inputs(void);
void test_fsm_precharge_rejects_stale_bus_reading(void);
void test_fsm_start_blocks_while_bleed_connected(void);
void test_fsm_start_blocks_while_link_charged(void);
void test_fsm_start_not_blocked_by_older_ecu(void);
void test_fsm_charger_arms_regardless_of_discharge_state(void);
void test_fsm_start_blocks_on_unmeasured_link(void);
void test_fsm_precharge_holds_on_unmeasured_link(void);
void test_fsm_charger_arms_with_unmeasured_link(void);
void test_fsm_older_ecu_arms_with_default_validity(void);
void test_fsm_transition_rejects_stale_bus_reading(void);
void test_fsm_charger_precharge_unaffected_by_stale_bus(void);
void test_fsm_start_to_precharge_charger_skips_precharge(void);
void test_fsm_precharge_reaches_target(void);
void test_fsm_precharge_stays_below_target(void);
void test_fsm_transition_commits_to_run_in_car_mode(void);
void test_fsm_transition_commits_to_charge_in_charger_mode(void);
void test_fsm_transition_undecided_mode_forces_error(void);
void test_fsm_transition_drops_voltage_to_error(void);
void test_fsm_precharge_times_out_to_error(void);
void test_fsm_precharge_holds_within_deadline(void);
void test_fsm_run_stays_while_tsms_and_dash_chg_high(void);
void test_fsm_run_to_start_on_tsms_drop(void);
void test_fsm_run_stays_on_dash_chg_release(void);
void test_fsm_charge_to_error_on_tsms_drop(void);
void test_fsm_charger_precharge_to_error_on_tsms_drop(void);
void test_fsm_precharge_to_start_on_tsms_drop(void);
void test_fsm_tsms_drop_still_yields_to_predicate_fault(void);
void test_fsm_charge_stays_on_dash_chg_release(void);
void test_fsm_run_to_start_on_bus_collapse(void);
void test_fsm_run_stays_when_bus_healthy(void);
void test_bus_below_collapse_thresholds(void);
void test_fsm_precharge_charger_proceeds_on_fresh_request(void);
void test_fsm_precharge_charger_holds_without_fresh_request(void);
void test_fsm_any_state_to_error_on_fault(void);
void test_fsm_error_is_sticky(void);

// test_ltc6811_decode.cpp
void test_ltc6811_pec_datasheet_wrcfga(void);
void test_ltc6811_pec_empty(void);
void test_ltc6811_pec_deterministic(void);
void test_ltc6811_pec_sensitivity(void);
void test_ltc6811_pec_lsb_is_zero(void);
void test_ltc6811_pack_command_wrcfga(void);
void test_ltc6811_pack_command_rdcva(void);
void test_ltc6811_adcv_norm_dcp1_all_cells(void);
void test_ltc6811_adcv_norm_dcp0_all_cells(void);
void test_ltc6811_adax_norm_all_aux(void);
void test_ltc6811_decode_cell_voltage_roundtrip(void);
void test_ltc6811_decode_cell_voltage_bad_pec(void);
void test_ltc6811_decode_aux_voltage_roundtrip(void);
void test_ltc6811_build_write_frame_chain10(void);
void test_ltc6811_build_write_frame_short_buffer_safe(void);
void test_ltc6811_pack_adg731_channel_5(void);
void test_ltc6811_pack_adg731_channel_0(void);
void test_ltc6811_pack_adg731_channel_31(void);
void test_ltc6811_pack_adg731_channel_masked(void);
void test_ltc6811_chain_discovery_all_ten_valid(void);
void test_ltc6811_chain_discovery_nine_then_bad(void);
void test_ltc6811_chain_discovery_ten_plus_trailing_garbage(void);
void test_ltc6811_chain_discovery_first_bad(void);
void test_ltc6811_chain_discovery_short_buffer(void);
void test_ltc6811_chain_discovery_null_safe(void);

// test_telemetry_encoders.cpp
void test_telem_status_layout(void);
void test_telem_status_ams_ok_normalised(void);
void test_telem_pack_layout_positive_current(void);
void test_telem_pack_layout_negative_current(void);
void test_telem_temps_layout(void);
void test_telem_temps_clip_to_int8_range(void);
void test_telem_temps_cockpit_byte_at_byte5(void);
void test_telem_temps_heartbeat_passthrough(void);
void test_telem_field_independence(void);

// test_pit_diag_emitter.cpp
void test_pit_diag_cell_frame_zero_indexes_module0(void);
void test_pit_diag_cell_frame_spans_module_boundary(void);
void test_pit_diag_cell_frame_last_has_sentinels(void);
void test_pit_diag_cell_frame_out_of_range_returns_zeros(void);
void test_pit_diag_temp_frame_first_byte_is_module0_temp0(void);
void test_pit_diag_temp_frame_clips_int8_range(void);
void test_pit_diag_temp_frame_last_covers_module4(void);
void test_pit_diag_cell_frame_offline_module_is_sentinel(void);
void test_pit_diag_temp_frame_offline_module_is_sentinel(void);
void test_pit_diag_fsm_status_layout(void);
void test_pit_diag_fsm_status_fault_reason(void);
void test_pit_diag_fsm_status_pec_saturates(void);
void test_pit_diag_timing_layout(void);
void test_pit_diag_timing_clips_poll_at_ffff(void);
void test_pit_diag_classify_enable_returns_plus_one(void);
void test_pit_diag_classify_disable_returns_minus_one(void);
void test_pit_diag_classify_random_payload_returns_zero(void);
void test_pit_diag_classify_wrong_id_returns_zero(void);
void test_pit_diag_classify_wrong_dlc_returns_zero(void);
void test_pit_diag_balance_mask_a_module0_cell0(void);
void test_pit_diag_balance_mask_a_module4_cell8(void);
void test_pit_diag_balance_mask_b_carries_cycles(void);
void test_pit_diag_boot_diag_layout(void);
void test_pit_diag_post_mortem_clean_session_all_zero(void);
void test_pit_diag_post_mortem_after_stack_overflow(void);
void test_pit_diag_post_mortem_saturates_watermark_and_malloc(void);
void test_pit_diag_fw_id_layout(void);
void test_pit_diag_pec_per_ic_a_layout(void);
void test_pit_diag_pec_per_ic_b_layout(void);
void test_pit_diag_pec_per_ic_saturates(void);
void test_pit_diag_comms_health_layout(void);
void test_pit_diag_comms_health_zero_when_clean(void);
void test_pit_diag_comms_health_fields_independent(void);
void test_pit_encode_balance_health_layout(void);

// test_fw_health.cpp
void test_fw_health_reset_cause_priority(void);
void test_fw_health_encode_layout(void);
void test_fw_health_encode_clamps_heap(void);

// test_balance_controller.cpp
void test_balance_uniform_pack_no_discharge(void);
void test_balance_hysteresis_holds_a_selected_cell(void);
void test_balance_hysteresis_releases_below_stop(void);
void test_balance_hysteresis_settles_instead_of_toggling(void);
void test_balance_incumbent_wins_ties_against_newcomer(void);
void test_balance_cell_open_wire_blocks_even_operator_on(void);
void test_balance_ov_uv_block_balancing(void);
void test_balance_non_cell_faults_stay_overridable(void);

// test_soc_estimator.cpp
void test_soc_ocv_hits_breakpoints_exactly(void);
void test_soc_ocv_interpolates_midpoints(void);
void test_soc_ocv_clamps_outside_the_curve(void);
void test_soc_ocv_is_monotonic(void);
void test_soc_rest_gate_requires_low_current_and_settle(void);
void test_soc_counter_starts_unknown(void);
void test_soc_counter_ignores_updates_before_anchor(void);
void test_soc_counter_anchor_round_trips(void);
void test_soc_counter_discharge_lowers_soc(void);
void test_soc_counter_charge_raises_soc(void);
void test_soc_counter_small_currents_are_not_truncated(void);
void test_soc_counter_clamps_at_rails(void);
void test_soc_counter_rejects_implausible_gaps(void);
void test_soc_counter_invalidate_returns_to_unknown(void);
void test_soc_counter_net_zero_current_holds_soc(void);
void test_soc_counter_1C_discharge_empties_in_one_hour(void);
void test_soc_ocv_forward_inverse_round_trip(void);
void test_soc_ocv_slope_is_steeper_at_the_top(void);
void test_soc_r_int_matches_fitted_model(void);
void test_soc_r_int_falls_with_temperature(void);
void test_soc_ekf_starts_invalid_and_seeds(void);
void test_soc_ekf_predict_matches_coulomb_counting(void);
void test_soc_ekf_variance_grows_on_predict_shrinks_on_correct(void);
void test_soc_ekf_converges_from_a_wrong_seed(void);
void test_soc_ekf_trusts_voltage_less_under_load(void);
void test_soc_ekf_ignores_measurements_where_curve_is_flat(void);
void test_soc_ekf_rejects_implausible_gaps_like_cc(void);
void test_soc_ekf_invalidate_returns_to_unknown(void);
void test_soc_ekf_beats_coulomb_counting_with_a_biased_sensor(void);
void test_balance_per_module_enable_gates_modules(void);
void test_balance_single_hot_cell_in_charge(void);
void test_balance_caps_at_max_active_per_module(void);
void test_balance_disabled_outside_charge(void);
void test_balance_thermal_lockout(void);
void test_balance_disabled_when_temps_untrusted(void);
void test_balance_op_off_forces_no_discharge(void);
void test_balance_op_on_runs_outside_charge(void);
void test_balance_op_on_respects_temp_trust(void);
void test_balance_threshold_strict_inequality(void);
void test_balance_temp_trust_is_decoupled_from_fault_trust(void);
void test_balance_operator_toggle_is_reachable_on_this_build(void);
void test_balance_on_discharges_in_all_states_as_configured(void);
void test_balance_lockout_still_applies_with_trust_flag(void);
void test_balance_adjacency_predicate(void);
void test_balance_single_low_outlier_does_not_bleed_stack(void);
void test_balance_lowest_cell_not_selected(void);
void test_balance_real_imbalance_still_works_with_robust_floor(void);
void test_balance_no_two_adjacent_selected(void);
void test_balance_spread_still_reaches_cap(void);
void test_balance_spread_prefers_higher_cells(void);
void test_balance_spread_thins_a_cluster(void);
void test_balance_refuses_with_no_thermal_data(void);
void test_balance_operator_on_cannot_override_thermal_data_gate(void);
void test_balance_thermal_data_gate_boundary(void);
void test_balance_runs_with_partial_thermal_coverage(void);

// test_sil_scenarios.cpp
void test_sil_nominal_startup_to_run(void);
void test_sil_bms_dropout_in_run(void);
void test_sil_charger_path(void);
void test_sil_charger_disconnect_in_charge_faults(void);
void test_sil_tsms_drop_in_charge_latches_error(void);
void test_sil_tsms_drop_in_charger_precharge_latches_error(void);
void test_sil_tsms_drop_in_run_rearms(void);
void test_sil_bus_collapse_in_run_rearms(void);

// test_datalogging.cpp
void test_logring_empty_pop_false(void);
void test_logring_fifo_order(void);
void test_logring_fills_and_drops_newest(void);
void test_logring_wraparound_fifo(void);
void test_logring_size_tracking(void);
void test_logcsv_header_column_count(void);
void test_logcsv_row_matches_header_columns(void);
void test_logcsv_row_scalar_values(void);
void test_logcsv_row_cell_and_temp_values(void);
void test_logcsv_truncation_returns_zero(void);

// test_ntc_table.cpp
void test_ntc_table_is_strictly_decreasing(void);
void test_ntc_table_covers_expected_range(void);
void test_ntc_r25_is_10k(void);
void test_ntc_exact_table_points_round_trip(void);
void test_ntc_datasheet_resistances(void);
void test_ntc_divider_voltage_recovers_temperature(void);
void test_ntc_thresholds_are_now_true_degrees(void);
void test_ntc_interpolates_between_points(void);
void test_ntc_is_monotonic_over_the_whole_range(void);
void test_ntc_rejects_out_of_range_resistance(void);
void test_ntc_accepts_exact_endpoints(void);
void test_ntc_pullup_is_6k8(void);
void test_ntc_hot_endpoint_resolves_from_resistance(void);

// test_log_rotation.cpp
void test_logrot_empty_card_starts_at_zero(void);
void test_logrot_skips_sealed_files(void);
void test_logrot_orphan_tmp_does_not_reuse_index(void);
void test_logrot_orphan_tmp_is_sealed(void);
void test_logrot_seals_every_orphan_on_the_way(void);
void test_logrot_failed_seal_still_consumes_index(void);
void test_logrot_tmp_beside_existing_csv_is_not_sealed(void);
void test_logrot_successive_runs_advance(void);
void test_logrot_rotates_on_size(void);
void test_logrot_rotates_on_time(void);
void test_logrot_time_rotation_needs_rows(void);
void test_logrot_fresh_file_does_not_rotate(void);
void test_logrot_time_cap_is_shorter_than_size_cap(void);
void test_logrot_file_age_normal(void);
void test_logrot_file_age_inverted_pair_is_zero(void);

int main(void) {
    UNITY_BEGIN();

        RUN_TEST(test_cell_open_range_budget_under_500ms);
    RUN_TEST(test_module_loss_budget_under_500ms);
    RUN_TEST(test_bms_open_wire_flags_module);
    RUN_TEST(test_bms_open_wire_pec_glitch_signals_retry);
    RUN_TEST(test_bms_open_wire_retry_preserves_confirmed_open);
    RUN_TEST(test_bms_capture_adow_raw_decodes_grids);
    RUN_TEST(test_bms_capture_cell_raw_decodes_grid);
RUN_TEST(test_bms_ltc_clean_response_decodes_all_cells);
    RUN_TEST(test_bms_tap_artifact_does_not_trip_ov);
    RUN_TEST(test_bms_real_overvoltage_not_masked);
    RUN_TEST(test_bms_nonphysical_without_compensation_not_masked);
    RUN_TEST(test_bms_ltc_pec_fail_on_one_ic_marks_module_stale);
    RUN_TEST(test_bms_ltc_pec_fail_increments_error_counter);
    RUN_TEST(test_bms_ltc_short_buffer_rejected);
    RUN_TEST(test_bms_ltc_null_buffer_rejected);
    RUN_TEST(test_bms_ltc_is_healthy_false_after_staleness);
    RUN_TEST(test_bms_mask_collapses_when_chain_stops_responding);
    RUN_TEST(test_bms_mask_clears_only_stale_modules);
    RUN_TEST(test_bms_temp_sweep_room_temp_on_one_channel);
    RUN_TEST(test_bms_temp_hotter_voltage_gives_hotter_reading);
    RUN_TEST(test_bms_temp_rail_reading_skips_slot);
    RUN_TEST(test_bms_temp_pec_fail_skips_slot);
    RUN_TEST(test_bms_temp_bad_channel_idx_rejected);
    RUN_TEST(test_bms_temp_disconnect_debounce);
    RUN_TEST(test_bms_temp_partial_rail_open_is_disconnect);
    RUN_TEST(test_bms_unpopulated_channel_is_not_a_disconnect);
    RUN_TEST(test_bms_required_channel_open_at_boot_faults);
    RUN_TEST(test_temp_disconnect_budget_under_500ms);
    RUN_TEST(test_bms_temp_short_buffer_rejected);
    RUN_TEST(test_bms_per_module_v_aggregates_after_clean_response);
    RUN_TEST(test_bms_per_module_tmax_after_temp_sweep);

    RUN_TEST(test_acu_tx_ok_precharge_high_in_run);
    RUN_TEST(test_acu_tx_ok_precharge_high_in_charge);
    RUN_TEST(test_acu_tx_ok_precharge_low_in_start);
    RUN_TEST(test_acu_tx_ok_precharge_low_in_precharge_and_transition);
    RUN_TEST(test_acu_tx_ok_precharge_low_in_error);
    RUN_TEST(test_acu_tx_min_voltage_big_endian);
    RUN_TEST(test_acu_tx_vmin_module_a_layout);
    RUN_TEST(test_acu_tx_vmin_module_b_layout);
    RUN_TEST(test_acu_tx_vmax_module_a_layout);
    RUN_TEST(test_acu_tx_vmax_module_b_layout);
    RUN_TEST(test_acu_tx_currents_zero);
    RUN_TEST(test_acu_tx_currents_positive_pack);
    RUN_TEST(test_acu_tx_currents_negative_pack_two_complement);
    RUN_TEST(test_acu_tx_currents_rounding_to_nearest_dA);
    RUN_TEST(test_acu_tx_currents_saturates_at_int16_extremes);
    RUN_TEST(test_acu_tx_currents_dcdc_in_bytes_2_3);
    RUN_TEST(test_acu_tx_tmax_module_a_layout);
    RUN_TEST(test_acu_tx_tmax_module_b_includes_dcdc_stub);
    RUN_TEST(test_acu_tx_tmax_handles_negative_degC);
    RUN_TEST(test_acu_tx_soc_stub_returns_unknown_sentinel);

    RUN_TEST(test_current_adc_zero_point_reads_near_zero);
    RUN_TEST(test_current_adc_discharge_positive);
    RUN_TEST(test_current_adc_charge_negative);
    RUN_TEST(test_current_adc_symmetric_around_zero);
    RUN_TEST(test_current_adc_over_limit_is_observable);
    RUN_TEST(test_current_adc_full_scale_rails);
    RUN_TEST(test_current_dcdc_zero_and_discharge);
    RUN_TEST(test_current_leg_voltage_window);
    RUN_TEST(test_current_update_sets_sensor_fault);
    RUN_TEST(test_current_is_dcdc_fresh_lifecycle);

    RUN_TEST(test_decode_dc_bus_little_endian);
    RUN_TEST(test_update_dc_bus_frame);
    RUN_TEST(test_dc_bus_byte2_bits_decode);
    RUN_TEST(test_dc_bus_dlc2_defaults_are_asymmetric);
    RUN_TEST(test_acu_frame_on_wrong_bus_rejected);
    RUN_TEST(test_charge_req_magic_frame_sets_tick);
    RUN_TEST(test_charge_req_wrong_magic_ignored);
    RUN_TEST(test_charge_requested_freshness);
    RUN_TEST(test_balance_override_balo_off);
    RUN_TEST(test_balance_override_baln_on);
    RUN_TEST(test_balance_override_balx_auto);
    RUN_TEST(test_balance_override_wrong_magic_ignored);
    RUN_TEST(test_balance_effective_cmd_freshness);
    RUN_TEST(test_balance_modules_decode);
    RUN_TEST(test_balance_modules_wrong_magic_ignored);
    RUN_TEST(test_balance_modules_effective_freshness);
    RUN_TEST(test_acu_unknown_id_rejected);

    RUN_TEST(test_isotp_round_trip_single_frame);
    RUN_TEST(test_isotp_round_trip_first_multiframe);
    RUN_TEST(test_isotp_round_trip_sequence_wrap);
    RUN_TEST(test_isotp_round_trip_max_message);
    RUN_TEST(test_isotp_segmenter_pins_wire_encoding);
    RUN_TEST(test_isotp_flow_control_frame_format);
    RUN_TEST(test_isotp_ff_raises_flow_control_pending);
    RUN_TEST(test_isotp_rejects_bad_single_frame_length);
    RUN_TEST(test_isotp_rejects_first_frame_that_should_be_single);
    RUN_TEST(test_isotp_rejects_oversized_message);
    RUN_TEST(test_isotp_rejects_consecutive_without_first);
    RUN_TEST(test_isotp_rejects_out_of_order_sequence);
    RUN_TEST(test_isotp_rejects_consecutive_from_other_peer);
    RUN_TEST(test_isotp_reassembly_times_out);
    RUN_TEST(test_isotp_idle_never_times_out);
    RUN_TEST(test_isotp_ignores_received_flow_control);
    RUN_TEST(test_isotp_recovers_after_error);
    RUN_TEST(test_isotp_segmenter_rejects_invalid_input);

    RUN_TEST(test_diag_msgtype_app_ctrl_is_0x06);
    RUN_TEST(test_diag_logfs_opcodes);
    RUN_TEST(test_diag_nack_codes_do_not_collide_with_bootloader);
    RUN_TEST(test_diag_logfs_entry_is_22_bytes);
    RUN_TEST(test_diag_list_batch_fits_one_isotp_message);
    RUN_TEST(test_diag_put_u16_is_little_endian);
    RUN_TEST(test_diag_put_u32_is_little_endian);
    RUN_TEST(test_diag_le_helpers_handle_extremes);
    RUN_TEST(test_diag_parse_request_extracts_type_opcode_args);
    RUN_TEST(test_diag_parse_request_no_args);
    RUN_TEST(test_diag_parse_request_rejects_runt);
    RUN_TEST(test_diag_parse_request_flags_non_app_ctrl);
    RUN_TEST(test_diag_build_ack_frames_type_and_opcode);
    RUN_TEST(test_diag_build_ack_empty_payload);
    RUN_TEST(test_diag_build_ack_refuses_overflow);
    RUN_TEST(test_diag_build_nack_is_three_bytes);
    RUN_TEST(test_diag_session_starts_closed);
    RUN_TEST(test_diag_session_connect_disconnect);
    RUN_TEST(test_diag_session_rejects_other_peer);
    RUN_TEST(test_diag_session_expires_when_host_walks_away);
    RUN_TEST(test_diag_session_traffic_refreshes_idle_timer);

    RUN_TEST(test_logfs_list_returns_all_entries);
    RUN_TEST(test_logfs_list_entry_layout);
    RUN_TEST(test_logfs_list_cursor_past_end_is_empty);
    RUN_TEST(test_logfs_list_paginates_when_reply_is_full);
    RUN_TEST(test_logfs_list_fs_error_nacks);
    RUN_TEST(test_logfs_open_returns_handle_and_size);
    RUN_TEST(test_logfs_open_missing_file_nacks);
    RUN_TEST(test_logfs_reopen_supersedes_and_closes_previous);
    RUN_TEST(test_logfs_close_releases_handle);
    RUN_TEST(test_logfs_release_closes_open_file);
    RUN_TEST(test_logfs_read_returns_requested_bytes);
    RUN_TEST(test_logfs_read_past_eof_is_short_ack_not_error);
    RUN_TEST(test_logfs_read_clamps_oversized_request);
    RUN_TEST(test_logfs_read_with_stale_handle_nacks);
    RUN_TEST(test_logfs_read_without_open_nacks);
    RUN_TEST(test_logfs_read_io_error_nacks);
    RUN_TEST(test_logfs_read_truncated_args_nacks);
    RUN_TEST(test_logfs_crc_returns_value);
    RUN_TEST(test_logfs_crc_error_nacks);
    RUN_TEST(test_logfs_no_card_nacks_every_opcode);
    RUN_TEST(test_logfs_owns_only_its_opcodes);
    RUN_TEST(test_logfs_unknown_opcode_nacks_unsupported);
    RUN_TEST(test_logfs_full_file_pull_sequence);
    RUN_TEST(test_logfs_open_reply_is_ten_bytes);
    RUN_TEST(test_logfs_open_reports_zero_crc_when_no_sidecar);
    RUN_TEST(test_logfs_finalize_seals_and_returns_index);
    RUN_TEST(test_logfs_finalize_refuses_when_nothing_written);
    RUN_TEST(test_logfs_finalize_releases_open_handle);
    RUN_TEST(test_logfs_finalize_no_card_nacks);
    RUN_TEST(test_logfs_owns_finalize_but_not_delete);

    RUN_TEST(test_crc32_check_vector);
    RUN_TEST(test_crc32_empty_is_zero);
    RUN_TEST(test_crc32_short_vectors);
    RUN_TEST(test_crc32_csv_header_shape);
    RUN_TEST(test_crc32_zero_filled_block);
    RUN_TEST(test_crc32_incremental_matches_one_shot);
    RUN_TEST(test_crc32_byte_at_a_time_matches);
    RUN_TEST(test_crc32_zero_length_update_is_identity);
    RUN_TEST(test_crc32_finalize_is_not_idempotent);
    RUN_TEST(test_crc32_detects_single_bit_flip);
    RUN_TEST(test_crc32_detects_reordering);

    RUN_TEST(test_dispatch_ignores_bootloader_namespace);
    RUN_TEST(test_dispatch_ignores_runt_message);
    RUN_TEST(test_dispatch_refuses_logfs_without_session);
    RUN_TEST(test_dispatch_connect_then_logfs_reaches_server);
    RUN_TEST(test_dispatch_refuses_logfs_from_other_peer);
    RUN_TEST(test_dispatch_new_connect_takes_over_and_releases);
    RUN_TEST(test_dispatch_connect_is_idempotent);
    RUN_TEST(test_dispatch_disconnect_releases_and_closes_session);
    RUN_TEST(test_dispatch_disconnect_without_session_still_acks);
    RUN_TEST(test_dispatch_tick_expires_session_and_releases);
    RUN_TEST(test_dispatch_traffic_keeps_long_transfer_alive);
    RUN_TEST(test_dispatch_unknown_opcode_nacks);
    RUN_TEST(test_dispatch_delete_opcode_is_unsupported);
    RUN_TEST(test_dispatch_session_check_precedes_opcode_check);
    RUN_TEST(test_dispatch_connect_ack_carries_protocol_version);
    RUN_TEST(test_dispatch_refuses_logfs_with_ts_live);
    RUN_TEST(test_dispatch_allows_logfs_in_start);
    RUN_TEST(test_dispatch_gate_covers_every_logfs_opcode);
    RUN_TEST(test_dispatch_session_ops_work_in_any_state);
    RUN_TEST(test_dispatch_releases_handle_when_car_goes_live);
    RUN_TEST(test_dispatch_error_state_is_permitted);
    RUN_TEST(test_dispatch_permitted_states_are_ts_down);
    RUN_TEST(test_bootloader_trigger_exact_match);
    RUN_TEST(test_bootloader_reboot_only_when_contactors_open);
    RUN_TEST(test_bootloader_trigger_still_matches_while_energised);
    RUN_TEST(test_bootloader_trigger_wrong_bus);
    RUN_TEST(test_bootloader_trigger_wrong_id);
    RUN_TEST(test_bootloader_trigger_wrong_dlc);
    RUN_TEST(test_bootloader_trigger_each_magic_byte_flipped);
    RUN_TEST(test_bootloader_trigger_trailing_bytes_ignored);

    RUN_TEST(test_busoff_healthy_bus_never_attempts);
    RUN_TEST(test_busoff_first_detection_attempts_immediately);
    RUN_TEST(test_busoff_sustained_is_rate_limited);
    RUN_TEST(test_busoff_boundary_exactly_retry_ms_attempts);
    RUN_TEST(test_busoff_steady_cadence_of_attempts);
    RUN_TEST(test_busoff_recovers_then_refaults_attempts_immediately);
    RUN_TEST(test_busoff_tick_wrap_preserves_spacing);

    RUN_TEST(test_predicates_nominal_no_fault);
    RUN_TEST(test_predicates_force_error);
    RUN_TEST(test_predicates_cell_undervoltage);
    RUN_TEST(test_predicates_cell_overvoltage);
    RUN_TEST(test_predicates_cell_overtemp);
    RUN_TEST(test_predicates_bms_stale);
    RUN_TEST(test_predicates_current_overlimit);
    RUN_TEST(test_predicates_current_stale);
    RUN_TEST(test_predicates_vcu_stale);
    RUN_TEST(test_predicates_temp_sensor_disconnected);
    RUN_TEST(test_predicates_temp_disconnect_independent_of_temp_trust);
    RUN_TEST(test_predicates_no_disconnect_no_fault);
    RUN_TEST(test_predicates_cell_open_wire_follows_flag);
    RUN_TEST(test_adow_cmd_encoding);
    RUN_TEST(test_open_wire_none_when_healthy);
    RUN_TEST(test_open_wire_interior_conductor);
    RUN_TEST(test_open_wire_endpoints);
    RUN_TEST(test_open_wire_bench_healthy_no_false_positive);
    RUN_TEST(test_open_wire_bench_open_conductor_detected);
    RUN_TEST(test_open_wire_conductor_to_cell_mapping);
    RUN_TEST(test_open_wire_input_guards);
    RUN_TEST(test_predicates_disconnect_is_immediate_not_range_debounced);
    RUN_TEST(test_predicates_boot_grace_suppresses_data_predicates);
    RUN_TEST(test_predicates_boot_grace_does_not_suppress_force_error);
    RUN_TEST(test_predicates_after_grace_zero_ticks_faults);
    RUN_TEST(test_predicates_future_tick_not_stale);
    RUN_TEST(test_predicates_tick_age_clamps_future);
    RUN_TEST(test_predicates_reason_none_when_nominal);
    RUN_TEST(test_predicates_reason_force_error);
    RUN_TEST(test_predicates_reason_bms_stale_reports_module);
    RUN_TEST(test_predicates_reason_current_stale);
    RUN_TEST(test_predicates_reason_vcu_stale);
    RUN_TEST(test_predicates_vcu_stale_exempt_when_not_car);
    RUN_TEST(test_predicates_charger_stale_faults_in_charger_mode);
    RUN_TEST(test_predicates_charger_stale_exempt_when_not_charger);
    RUN_TEST(test_fsm_error_reason_charger_tsms_open);
    RUN_TEST(test_predicates_undervoltage_suppressed_before_first_poll);
    RUN_TEST(test_predicates_undervoltage_armed_reports_module);
    RUN_TEST(test_predicates_offline_module_trips_regardless_of_gate);
    RUN_TEST(test_module_below_sentinel_when_none);
    RUN_TEST(test_is_cell_range_reason);
    RUN_TEST(test_cell_debounce_confirms_after_n);
    RUN_TEST(test_cell_debounce_transient_never_confirms);
    RUN_TEST(test_cell_debounce_reason_change_resets);
    RUN_TEST(test_cell_debounce_ignores_non_cell);
    RUN_TEST(test_bms_stale_debounce_confirms_after_n);
    RUN_TEST(test_bms_stale_debounce_transient_never_confirms);
    RUN_TEST(test_bms_stale_debounce_resets_on_other_reason);
    RUN_TEST(test_ams_ok_low_during_grace);
    RUN_TEST(test_ams_ok_high_when_healthy_post_grace);
    RUN_TEST(test_ams_ok_low_when_latched);

    RUN_TEST(test_dsl_status_matches_handrolled);
    RUN_TEST(test_dsl_status_roundtrip);
    RUN_TEST(test_dsl_pack_matches_handrolled_discharge);
    RUN_TEST(test_dsl_pack_matches_handrolled_charge);
    RUN_TEST(test_dsl_pack_roundtrip_signed);
    RUN_TEST(test_dsl_temps_matches_handrolled);
    RUN_TEST(test_dsl_temps_roundtrip_negative);
    RUN_TEST(test_dsl_relay_status_matches_handrolled);
    RUN_TEST(test_dsl_registry_well_formed);
    RUN_TEST(test_dsl_descriptors_match_committed_dbc);
    RUN_TEST(test_dsl_array_descriptors_match_committed_dbc);

    RUN_TEST(test_fsm_start_waits_without_tsms_or_dash_chg);
    RUN_TEST(test_fsm_start_waits_with_tsms_only);
    RUN_TEST(test_fsm_start_waits_with_dash_chg_only);
    RUN_TEST(test_fsm_start_to_precharge_on_both_inputs);
    RUN_TEST(test_fsm_precharge_rejects_stale_bus_reading);
    RUN_TEST(test_fsm_start_blocks_while_bleed_connected);
    RUN_TEST(test_fsm_start_blocks_while_link_charged);
    RUN_TEST(test_fsm_start_not_blocked_by_older_ecu);
    RUN_TEST(test_fsm_charger_arms_regardless_of_discharge_state);
    RUN_TEST(test_fsm_start_blocks_on_unmeasured_link);
    RUN_TEST(test_fsm_precharge_holds_on_unmeasured_link);
    RUN_TEST(test_fsm_charger_arms_with_unmeasured_link);
    RUN_TEST(test_fsm_older_ecu_arms_with_default_validity);
    RUN_TEST(test_fsm_transition_rejects_stale_bus_reading);
    RUN_TEST(test_fsm_charger_precharge_unaffected_by_stale_bus);
    RUN_TEST(test_fsm_start_to_precharge_charger_skips_precharge);
    RUN_TEST(test_fsm_precharge_reaches_target);
    RUN_TEST(test_fsm_precharge_stays_below_target);
    RUN_TEST(test_fsm_transition_commits_to_run_in_car_mode);
    RUN_TEST(test_fsm_transition_commits_to_charge_in_charger_mode);
    RUN_TEST(test_fsm_transition_undecided_mode_forces_error);
    RUN_TEST(test_fsm_transition_drops_voltage_to_error);
    RUN_TEST(test_fsm_precharge_times_out_to_error);
    RUN_TEST(test_fsm_precharge_holds_within_deadline);
    RUN_TEST(test_fsm_run_stays_while_tsms_and_dash_chg_high);
    RUN_TEST(test_fsm_run_to_start_on_tsms_drop);
    RUN_TEST(test_fsm_run_stays_on_dash_chg_release);
    RUN_TEST(test_fsm_charge_to_error_on_tsms_drop);
    RUN_TEST(test_fsm_charger_precharge_to_error_on_tsms_drop);
    RUN_TEST(test_fsm_precharge_to_start_on_tsms_drop);
    RUN_TEST(test_fsm_tsms_drop_still_yields_to_predicate_fault);
    RUN_TEST(test_fsm_charge_stays_on_dash_chg_release);
    RUN_TEST(test_fsm_run_to_start_on_bus_collapse);
    RUN_TEST(test_fsm_run_stays_when_bus_healthy);
    RUN_TEST(test_bus_below_collapse_thresholds);
    RUN_TEST(test_fsm_precharge_charger_proceeds_on_fresh_request);
    RUN_TEST(test_fsm_precharge_charger_holds_without_fresh_request);
    RUN_TEST(test_fsm_any_state_to_error_on_fault);
    RUN_TEST(test_fsm_error_is_sticky);

    RUN_TEST(test_ltc6811_pec_datasheet_wrcfga);
    RUN_TEST(test_ltc6811_pec_empty);
    RUN_TEST(test_ltc6811_pec_deterministic);
    RUN_TEST(test_ltc6811_pec_sensitivity);
    RUN_TEST(test_ltc6811_pec_lsb_is_zero);
    RUN_TEST(test_ltc6811_pack_command_wrcfga);
    RUN_TEST(test_ltc6811_pack_command_rdcva);
    RUN_TEST(test_ltc6811_adcv_norm_dcp1_all_cells);
    RUN_TEST(test_ltc6811_adcv_norm_dcp0_all_cells);
    RUN_TEST(test_ltc6811_adax_norm_all_aux);
    RUN_TEST(test_ltc6811_decode_cell_voltage_roundtrip);
    RUN_TEST(test_ltc6811_decode_cell_voltage_bad_pec);
    RUN_TEST(test_ltc6811_decode_aux_voltage_roundtrip);
    RUN_TEST(test_ltc6811_build_write_frame_chain10);
    RUN_TEST(test_ltc6811_build_write_frame_short_buffer_safe);
    RUN_TEST(test_ltc6811_pack_adg731_channel_5);
    RUN_TEST(test_ltc6811_pack_adg731_channel_0);
    RUN_TEST(test_ltc6811_pack_adg731_channel_31);
    RUN_TEST(test_ltc6811_pack_adg731_channel_masked);
    RUN_TEST(test_ltc6811_chain_discovery_all_ten_valid);
    RUN_TEST(test_ltc6811_chain_discovery_nine_then_bad);
    RUN_TEST(test_ltc6811_chain_discovery_ten_plus_trailing_garbage);
    RUN_TEST(test_ltc6811_chain_discovery_first_bad);
    RUN_TEST(test_ltc6811_chain_discovery_short_buffer);
    RUN_TEST(test_ltc6811_chain_discovery_null_safe);

    RUN_TEST(test_telem_status_layout);
    RUN_TEST(test_telem_status_ams_ok_normalised);
    RUN_TEST(test_telem_pack_layout_positive_current);
    RUN_TEST(test_telem_pack_layout_negative_current);
    RUN_TEST(test_telem_temps_layout);
    RUN_TEST(test_telem_temps_clip_to_int8_range);
    RUN_TEST(test_telem_temps_cockpit_byte_at_byte5);
    RUN_TEST(test_telem_temps_heartbeat_passthrough);
    RUN_TEST(test_telem_field_independence);

    RUN_TEST(test_pit_diag_cell_frame_zero_indexes_module0);
    RUN_TEST(test_pit_diag_cell_frame_spans_module_boundary);
    RUN_TEST(test_pit_diag_cell_frame_last_has_sentinels);
    RUN_TEST(test_pit_diag_cell_frame_out_of_range_returns_zeros);
    RUN_TEST(test_pit_diag_temp_frame_first_byte_is_module0_temp0);
    RUN_TEST(test_pit_diag_temp_frame_clips_int8_range);
    RUN_TEST(test_pit_diag_temp_frame_last_covers_module4);
    RUN_TEST(test_pit_diag_cell_frame_offline_module_is_sentinel);
    RUN_TEST(test_pit_diag_temp_frame_offline_module_is_sentinel);
    RUN_TEST(test_pit_diag_fsm_status_layout);
    RUN_TEST(test_pit_diag_fsm_status_fault_reason);
    RUN_TEST(test_pit_diag_fsm_status_pec_saturates);
    RUN_TEST(test_pit_diag_timing_layout);
    RUN_TEST(test_pit_diag_timing_clips_poll_at_ffff);
    RUN_TEST(test_pit_diag_classify_enable_returns_plus_one);
    RUN_TEST(test_pit_diag_classify_disable_returns_minus_one);
    RUN_TEST(test_pit_diag_classify_random_payload_returns_zero);
    RUN_TEST(test_pit_diag_classify_wrong_id_returns_zero);
    RUN_TEST(test_pit_diag_classify_wrong_dlc_returns_zero);
    RUN_TEST(test_pit_diag_balance_mask_a_module0_cell0);
    RUN_TEST(test_pit_diag_balance_mask_a_module4_cell8);
    RUN_TEST(test_pit_diag_balance_mask_b_carries_cycles);
    RUN_TEST(test_pit_diag_boot_diag_layout);
    RUN_TEST(test_pit_diag_post_mortem_clean_session_all_zero);
    RUN_TEST(test_pit_diag_post_mortem_after_stack_overflow);
    RUN_TEST(test_pit_diag_post_mortem_saturates_watermark_and_malloc);
    RUN_TEST(test_pit_diag_fw_id_layout);
    RUN_TEST(test_pit_diag_pec_per_ic_a_layout);
    RUN_TEST(test_pit_diag_pec_per_ic_b_layout);
    RUN_TEST(test_pit_diag_pec_per_ic_saturates);
    RUN_TEST(test_pit_diag_comms_health_layout);
    RUN_TEST(test_pit_diag_comms_health_zero_when_clean);
    RUN_TEST(test_pit_diag_comms_health_fields_independent);
    RUN_TEST(test_pit_encode_balance_health_layout);

    RUN_TEST(test_fw_health_reset_cause_priority);
    RUN_TEST(test_fw_health_encode_layout);
    RUN_TEST(test_fw_health_encode_clamps_heap);

    RUN_TEST(test_balance_uniform_pack_no_discharge);
    RUN_TEST(test_balance_hysteresis_holds_a_selected_cell);
    RUN_TEST(test_balance_hysteresis_releases_below_stop);
    RUN_TEST(test_balance_hysteresis_settles_instead_of_toggling);
    RUN_TEST(test_balance_incumbent_wins_ties_against_newcomer);
    RUN_TEST(test_balance_cell_open_wire_blocks_even_operator_on);
    RUN_TEST(test_balance_ov_uv_block_balancing);
    RUN_TEST(test_balance_non_cell_faults_stay_overridable);
    RUN_TEST(test_soc_ocv_hits_breakpoints_exactly);
    RUN_TEST(test_soc_ocv_interpolates_midpoints);
    RUN_TEST(test_soc_ocv_clamps_outside_the_curve);
    RUN_TEST(test_soc_ocv_is_monotonic);
    RUN_TEST(test_soc_rest_gate_requires_low_current_and_settle);
    RUN_TEST(test_soc_counter_starts_unknown);
    RUN_TEST(test_soc_counter_ignores_updates_before_anchor);
    RUN_TEST(test_soc_counter_anchor_round_trips);
    RUN_TEST(test_soc_counter_discharge_lowers_soc);
    RUN_TEST(test_soc_counter_charge_raises_soc);
    RUN_TEST(test_soc_counter_small_currents_are_not_truncated);
    RUN_TEST(test_soc_counter_clamps_at_rails);
    RUN_TEST(test_soc_counter_rejects_implausible_gaps);
    RUN_TEST(test_soc_counter_invalidate_returns_to_unknown);
    RUN_TEST(test_soc_counter_net_zero_current_holds_soc);
    RUN_TEST(test_soc_counter_1C_discharge_empties_in_one_hour);
    RUN_TEST(test_soc_ocv_forward_inverse_round_trip);
    RUN_TEST(test_soc_ocv_slope_is_steeper_at_the_top);
    RUN_TEST(test_soc_r_int_matches_fitted_model);
    RUN_TEST(test_soc_r_int_falls_with_temperature);
    RUN_TEST(test_soc_ekf_starts_invalid_and_seeds);
    RUN_TEST(test_soc_ekf_predict_matches_coulomb_counting);
    RUN_TEST(test_soc_ekf_variance_grows_on_predict_shrinks_on_correct);
    RUN_TEST(test_soc_ekf_converges_from_a_wrong_seed);
    RUN_TEST(test_soc_ekf_trusts_voltage_less_under_load);
    RUN_TEST(test_soc_ekf_ignores_measurements_where_curve_is_flat);
    RUN_TEST(test_soc_ekf_rejects_implausible_gaps_like_cc);
    RUN_TEST(test_soc_ekf_invalidate_returns_to_unknown);
    RUN_TEST(test_soc_ekf_beats_coulomb_counting_with_a_biased_sensor);
    RUN_TEST(test_balance_per_module_enable_gates_modules);
    RUN_TEST(test_balance_single_hot_cell_in_charge);
    RUN_TEST(test_balance_caps_at_max_active_per_module);
    RUN_TEST(test_balance_disabled_outside_charge);
    RUN_TEST(test_balance_thermal_lockout);
    RUN_TEST(test_balance_disabled_when_temps_untrusted);
    RUN_TEST(test_balance_op_off_forces_no_discharge);
    RUN_TEST(test_balance_op_on_runs_outside_charge);
    RUN_TEST(test_balance_op_on_respects_temp_trust);
    RUN_TEST(test_balance_threshold_strict_inequality);
    RUN_TEST(test_balance_temp_trust_is_decoupled_from_fault_trust);
    RUN_TEST(test_balance_operator_toggle_is_reachable_on_this_build);
    RUN_TEST(test_balance_on_discharges_in_all_states_as_configured);
    RUN_TEST(test_balance_lockout_still_applies_with_trust_flag);
    RUN_TEST(test_balance_adjacency_predicate);
    RUN_TEST(test_balance_single_low_outlier_does_not_bleed_stack);
    RUN_TEST(test_balance_lowest_cell_not_selected);
    RUN_TEST(test_balance_real_imbalance_still_works_with_robust_floor);
    RUN_TEST(test_balance_no_two_adjacent_selected);
    RUN_TEST(test_balance_spread_still_reaches_cap);
    RUN_TEST(test_balance_spread_prefers_higher_cells);
    RUN_TEST(test_balance_spread_thins_a_cluster);
    RUN_TEST(test_balance_refuses_with_no_thermal_data);
    RUN_TEST(test_balance_operator_on_cannot_override_thermal_data_gate);
    RUN_TEST(test_balance_thermal_data_gate_boundary);
    RUN_TEST(test_balance_runs_with_partial_thermal_coverage);

    RUN_TEST(test_sil_nominal_startup_to_run);
    RUN_TEST(test_sil_bms_dropout_in_run);
    RUN_TEST(test_sil_charger_path);
    RUN_TEST(test_sil_charger_disconnect_in_charge_faults);
    RUN_TEST(test_sil_tsms_drop_in_charge_latches_error);
    RUN_TEST(test_sil_tsms_drop_in_charger_precharge_latches_error);
    RUN_TEST(test_sil_tsms_drop_in_run_rearms);
    RUN_TEST(test_sil_bus_collapse_in_run_rearms);

    RUN_TEST(test_logring_empty_pop_false);
    RUN_TEST(test_logring_fifo_order);
    RUN_TEST(test_logring_fills_and_drops_newest);
    RUN_TEST(test_logring_wraparound_fifo);
    RUN_TEST(test_logring_size_tracking);
    RUN_TEST(test_logcsv_header_column_count);
    RUN_TEST(test_logcsv_row_matches_header_columns);
    RUN_TEST(test_logcsv_row_scalar_values);
    RUN_TEST(test_logcsv_row_cell_and_temp_values);
    RUN_TEST(test_logcsv_truncation_returns_zero);

    RUN_TEST(test_ntc_table_is_strictly_decreasing);
    RUN_TEST(test_ntc_table_covers_expected_range);
    RUN_TEST(test_ntc_r25_is_10k);
    RUN_TEST(test_ntc_exact_table_points_round_trip);
    RUN_TEST(test_ntc_datasheet_resistances);
    RUN_TEST(test_ntc_divider_voltage_recovers_temperature);
    RUN_TEST(test_ntc_thresholds_are_now_true_degrees);
    RUN_TEST(test_ntc_interpolates_between_points);
    RUN_TEST(test_ntc_is_monotonic_over_the_whole_range);
    RUN_TEST(test_ntc_rejects_out_of_range_resistance);
    RUN_TEST(test_ntc_accepts_exact_endpoints);
    RUN_TEST(test_ntc_pullup_is_6k8);
    RUN_TEST(test_ntc_hot_endpoint_resolves_from_resistance);

    RUN_TEST(test_logrot_empty_card_starts_at_zero);
    RUN_TEST(test_logrot_skips_sealed_files);
    RUN_TEST(test_logrot_orphan_tmp_does_not_reuse_index);
    RUN_TEST(test_logrot_orphan_tmp_is_sealed);
    RUN_TEST(test_logrot_seals_every_orphan_on_the_way);
    RUN_TEST(test_logrot_failed_seal_still_consumes_index);
    RUN_TEST(test_logrot_tmp_beside_existing_csv_is_not_sealed);
    RUN_TEST(test_logrot_successive_runs_advance);
    RUN_TEST(test_logrot_rotates_on_size);
    RUN_TEST(test_logrot_rotates_on_time);
    RUN_TEST(test_logrot_time_rotation_needs_rows);
    RUN_TEST(test_logrot_fresh_file_does_not_rotate);
    RUN_TEST(test_logrot_time_cap_is_shorter_than_size_cap);
    RUN_TEST(test_logrot_file_age_normal);
    RUN_TEST(test_logrot_file_age_inverted_pair_is_zero);

    return UNITY_END();
}

}  // extern "C"
